---
# Part 1 Provisioning application
#- name: prepare apache
- hosts: web
  become: yes

  roles:
    - deploy_LAMP

#==========================================================================
  tasks:
#   Download repo from github (we need to waiting for ending this task)
    - name: Upload App to the temp Directory
      ansible.builtin.git:
        repo: https://github.com/FaztWeb/php-mysql-crud.git
        dest: "/tmp/{{virual_domain}}"

# Replays folder with items to apache work directory (!!!After previous task finished)
    - name: Copy Uploaded app from temp to multiple site location
      ansible.builtin.copy:
        src: "/tmp/{{virual_domain}}"
        dest: /var/www/
        remote_src: yes


# Place DB connection file to application folder   (!!! After Activate site)
    - name: Copy db.php.j2 file to /var/www/"{{virual_domain}}"
      template:
        src: /Users/vital/PycharmProjects/ansible_lab2/db.php.j2
        dest: "/var/www/{{virual_domain}}/db.php"



#================ Create Database=============================
- hosts: db
  become: yes

  roles:
    - deploy_mysql

  tasks:
    - name: Create a new database with name "{{ db_name }}"
      mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: "{{ app_db_name }}"
        state: present

    - name: Copy SQL file to target host
      ansible.builtin.copy:
        src: /Users/vital/PycharmProjects/ansible_lab2/script.sql
        dest: /tmp/script.sql


    - name: Create tables "{{ db_name }}"
      mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: "{{ app_db_name }}"
        state: import
        target: /tmp/script.sql



    - name: Create a new database user and password
      mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: "{{app_db_username}}"
        password: "{{app_db_password}}"
        priv: '{{app_db_name}}.*:ALL'
        host: "%"
        state: present


