---
# Part 1 Provisioning apache
- hosts: web
  vars_files:
    - "{{ inventory_dir }}/credentionals.yml"

  roles:

   - { role: deploy_LAMP, become: yes, http_port: 80,  when ansible_os_family == Ubuntu }
   - { role: deploy_crub, become: no, when ansible_os_family == Ubuntu }


#================ Deploy MySQL and create Database =============================
- hosts: db
  vars_files:
    - "{{ inventory_dir }}/credentionals.yml"
  roles:
    - { role: deploy_mysql, become: yes, when ansible_os_family == Ubuntu }
