---
# Plat 1 Install Appache on all servers in group web
- name: Install Appache
  hosts: web
  become: yes

  tasks:
    - name: Install the latest version of Apache
      ansible.builtin.apt:
        name: apache2
        state: latest

    - name: Start Apache and Enable Status Auto
      service: name=apache2 state=started enabled=yes


    - name: Installing PHP packages
      apt: pkg={{ item }}
      with_items:
        - python3-pip
        - php
        - libapache2-mod-php
        - php-mysql


# Play 2 Install MySql Database on servers in group db, and create empty database
- name: Install mysql server and initialize service
  hosts: db
  become: yes
  gather_facts: false

  tasks:
    - name: Install the latest version of MySql Server
      ansible.builtin.apt:
        name: mysql-server
        state: latest

    - name: Make sure a MySql service Started and running
      ansible.builtin.systemd:
        name: mysql.service
        state: started
        enabled: yes

    - name: Installing  python3-pip
      apt: pkg={{ item }}
      with_items:
        - python3-pip

    - name: Install pymysql for working with DataBase
      ansible.builtin.pip:
        name: pymysql

# Place my.cnf  connection file to /etc/mysql   (!!! After Activation restart)
    - name: Copy my.cnf file to config
      ansible.builtin.copy:
        src: /Users/vital/PycharmProjects/ansible_lab2/my.cnf
        dest: /etc/mysql/my.cnf
        remote_src: no
      notify:
        - restart mysql

  handlers:
    - name: restart mysql
      service: name=mysql state=restarted