---
# Plat 1 Install Appache on all servers in group web
- name: Install Appache
  hosts: web
  become: yes
  vars:
    virual_domain: 'crub.local'
    dest_folder: '/tmp/crub.local'

  tasks:
#   Download repo from github (we need to waiting for ending this task)
    - name: Upload App to the temp Directory
      ansible.builtin.git:
        repo: https://github.com/FaztWeb/php-mysql-crud.git
        dest: "{{dest_folder}}"

# Replays folder with items to apache work directory (!!!After previous task finished)
    - name: Copy Uploaded app from temp to multiple site location
      ansible.builtin.copy:
        src: "{{dest_folder}}"
        dest: /var/www/
        remote_src: yes

# Place virtual apache host config to distination   (!!! After Activate site)
    - name: Copy config file to /etc/apache2/sites-available/
      ansible.builtin.copy:
        src: /Users/vital/PycharmProjects/ansible_lab2/site.conf
        dest: "/etc/apache2/sites-available/{{virual_domain}}.conf"
        remote_src: no

# Apache activate virtual host (!!!! After Activation Restart Apache)
    - name: a2ensite {{ virual_domain }}
      command: a2ensite {{ virual_domain }}
      notify:
        - restart apache2

# Place DB connection file to application folder   (!!! After Activate site)
    - name: Copy db.php file to /var/www/"{{virual_domain}}"
      ansible.builtin.copy:
        src: /Users/vital/PycharmProjects/ansible_lab2/db.php
        dest: "/var/www/{{virual_domain}}/db.php"
        remote_src: no

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted