---
# handlers file for deploy_LAMP

- name: reload apache2
  service:
    name: apache2
    state: reloaded

- name: restart apache2
  service:
    name: apache2
    state: restarted

# Apache activate virtual host
- name: a2ensite {{ virual_domain }}
  command: a2ensite {{ virual_domain }}